### ISSUE TITLE
Version of jQuery Mobile not specified.

### ISSUE THREAD

**Issue by mariozaizar** [Guidecase/jquery_mobile-rails#1]
Hi, 

I'm wondering which version of JQM are you providing. 

I have some projects running the latest stable, but others uses the beta. So, it's important to me know (or even better) specify the version of JQM to use.  Are you going to provide access to beta, or just stable releases?

**Comment by Guidecase** [comment]
Hi,

Supporting the latest version right now - 1.2.0 - and updated the readme to reflect that. In the future the gem is likely to support beta releases, and will certainly support release candidates. Thanks!
