### ISSUE TITLE
Gem?

### ISSUE THREAD

**Issue by gwcoffey** [Guidecase/jquery_mobile-rails#2]
when I put gem 'jquery_mobile-rails' in my gemfile, per the read me, I get a different gem that hasn't been updated in ages and is built with a jqm 1.1.0 RC.

What is the correct way to get this gem? Do you build the gem somewhere?

Thanks!

Geoff

**Comment by TertiumQuid** [comment]
Hi Geoff,

You were probably pulling a similarly named package from rubygems. The gem should be referenced on github, like so:

```
gem "jquery_mobile-rails", :git => 'https://github.com/Guidecase/jquery_mobile-rails.git'
```

That should have originalyl been in the README, which I've just updated to include the github reference.

Thanks!

**Comment by gwcoffey** [comment]
Perfect. Thanks!
